[package]
name = "fuzz"
version = "0.1.0"
edition = "2018"

[dependencies]
itertools = "0.10"
number_prefix = "0.4"
rand = "0.8"
rand_distr = "0.4"
rand_regex = "0.15"
sapling.path = "../sapling"
sapling_grammar.path = "../grammar"
