name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
    - name: Run rustfmt
      run: rustfmt src/**/*.rs --check
    - name: Check docs
      run: |
          rustup update nightly
          cargo +nightly doc --no-deps --document-private-items
